import assert from 'node:assert/strict';
import { mkdtemp, rm } from 'node:fs/promises';
import { tmpdir } from 'node:os';
import path from 'node:path';
import { createLabelService } from './labels.mjs';

const directory = await mkdtemp(path.join(tmpdir(), 'lmd-label-test-'));
const root = path.join(directory, 'library');
const app = { libraries: [{ id: 'lib', path: root }], displayGroups: [], media: [] };
const add = (id, folder) => app.media.push({ id, libraryId: 'lib', fileName: `${id}.mkv`, path: path.join(root, folder, `${id}.mkv`), size: 10 });
add('01', 'work/season'); add('02', 'work/season'); add('03', 'other');
let time = 1000;
const options = { directory, getState: () => app, folderForMedia: m => path.dirname(m.path), stableId: p => path.relative(root, p) || 'root', episodeForMedia: m => Number(m.id), now: () => time, leaseMs: 100 };
const resultFor = batch => ({ batchId: batch.batchId, groups: batch.groups.map(g => ({ id: g.id, version: g.version, status: 'completed', titles: { title: '吹响吧！上低音号', originalTitle: '響け！ユーフォニアム', sources: ['https://anime-eupho.com/'], evidence: '固定测试资料，模拟作品及单集表对应。' }, episodes: [{ slot: 1, originalEpisodeTitle: 'あらたなユーフォニアム' }] })) });
try {
  let service = await createLabelService(options);
  assert.equal(service.status().pending, 2);
  for (const batchId of ['__proto__', 'constructor', 'toString', null, {}]) {
    await assert.rejects(service.release({ batchId }), /批次不存在/);
    assert.throws(() => service.validate({ batchId, groups: [] }), /批次不存在/);
  }
  assert.equal(Object.hasOwn(Object.prototype, 'closed'), false, 'invalid batch IDs cannot mutate shared object prototypes');
  const wholeLibrary = await service.claim({ scope: 'recursive' });
  assert.equal(wholeLibrary.groups.length, 2, 'recursive mode without selected IDs includes pending works across the library');
  await service.release({ batchId: wholeLibrary.batchId });
  assert.ok(service.targets().find(t => t.id === 'work'));
  const [a, b] = await Promise.all([service.claim({ id: 'work', scope: 'recursive' }), service.claim({ id: 'work', scope: 'recursive' })]);
  assert.equal(a.groups.length, 1); assert.equal(b.groups.length, 0);
  assert.ok(!JSON.stringify(a).includes(root));
  const result = resultFor(a);
  assert.throws(() => service.validate({ ...result, path: 'bad' }), /不允许字段/);
  const illegal = structuredClone(result); illegal.groups[0].titles.season = 2;
  assert.throws(() => service.validate(illegal), /不允许字段/);
  const insufficient = structuredClone(result); insufficient.groups[0].titles.sources = [];
  assert.throws(() => service.validate(insufficient), /缺少来源/);
  assert.equal(service.validate(result).valid, true);
  assert.equal((await service.apply(result)).success, 1);
  assert.equal((await service.apply(result)).duplicate, true);
  const rootTarget = service.targets().find(t => t.id === 'root');
  assert.equal(rootTarget.status, 'pending', 'one completed descendant must not mark the entire library completed');
  assert.equal(rootTarget.protected, false, 'a partly completed recursive range still has available work');
  assert.equal(rootTarget.directProtected, true, 'writing one title to the whole parent remains protected');
  assert.deepEqual(rootTarget.counts, { pending: 1, completed: 1, review: 0, claimed: 0, total: 2 });
  assert.equal((await service.claim({ id: 'root', scope: 'direct' })).groups.length, 0, 'recursive status must not weaken direct write protection');
  const resumed = await service.claim({ id: 'root' });
  assert.equal(resumed.groups.length, 1, 'default claim continues recursively after a completed child');
  assert.equal(resumed.groups[0].directory, 'other');
  await service.release({ batchId: resumed.batchId });
  assert.equal(service.status({ id: 'work' }).completed, 1);
  assert.equal(service.status({ id: 'work' }).pending, 0, 'scoped status excludes unrelated works');
  const byName = await service.claim({ folder: 'other' });
  assert.equal(byName.groups[0].id, 'other', 'an exact unique folder name resolves without paths');
  assert.equal(service.status({ folder: 'other' }).claimed, 1);
  await service.release({ batchId: byName.batchId });
  assert.equal(service.targets().find(t => t.id === 'other').parentId, 'root');
  assert.equal(service.media(app.media[0]).originalEpisodeTitle, 'あらたなユーフォニアム');
  add('04', 'work/season');
  assert.equal((await service.claim({ id: 'work', scope: 'recursive' })).groups.length, 0);
  service = await createLabelService(options);
  assert.equal(service.media(app.media[3]).title, '吹响吧！上低音号');
  const priorId = app.media[0].id;
  app.media[0].id = 'migrated-id';
  assert.equal(service.media(app.media[0]).originalEpisodeTitle, 'あらたなユーフォニアム');
  app.media[0].id = priorId;
  await service.manual('01', { title: '独立标题' });
  assert.equal(service.media(app.media[0]).title, '独立标题');
  assert.equal(service.media(app.media[0]).originalTitle, undefined);
  await service.manual('work', { clear: true });
  const intermediate = await service.claim({ id: 'work' });
  await service.manual('01', { title: '手动优先' });
  assert.throws(() => service.validate(resultFor(intermediate)), /手动修改优先/);
  await service.release({ batchId: intermediate.batchId });
  await service.manual('work', { clear: true });
  const single = await service.claim({ id: '01' });
  assert.equal(single.groups[0].kind, 'video');
  await service.release({ batchId: single.batchId });
  const expired = await service.claim({ id: '03' }); time += 101;
  assert.throws(() => service.validate(resultFor(expired)), /过期/);
  const review = await service.claim({ id: 'other' });
  await service.apply({ batchId: review.batchId, groups: [{ id: review.groups[0].id, version: review.groups[0].version, status: 'review', reason: '同名冲突' }] });
  assert.equal(service.status({ folder: 'other' }).review, 1);
  assert.equal(service.status({ folder: 'other' }).claimed, 0, 'review state is not misreported as an active claim');
  assert.equal((await service.claim({ id: 'other' })).groups.length, 0);
  assert.equal((await service.claim({ id: 'other', retry: true })).groups.length, 1);
  app.displayGroups.push({ id: 'work', path: path.join(root, 'work'), title: '旧标题' });
  // A previous explicit clear is a persistent tombstone; another legacy folder remains protected.
  add('05', 'legacy/sub'); app.displayGroups.push({ path: path.join(root, 'legacy'), title: '旧记录' });
  assert.equal((await service.claim({ id: path.join('legacy', 'sub') })).groups.length, 0);
  assert.equal((await service.claim({ id: 'root', scope: 'children' })).groups.length, 1);
  const driveRoot = path.parse(root).root;
  const driveApp = { libraries: [{ id: 'drive', path: driveRoot }], displayGroups: [], media: [{ id: 'drive-video', libraryId: 'drive', path: path.join(driveRoot, 'LmdRootFixture', 'video.mp4'), fileName: 'video.mp4' }] };
  const driveService = await createLabelService({ ...options, directory: path.join(directory, 'drive-labels'), getState: () => driveApp, stableId: p => p });
  assert.ok(driveService.targets().some(t => t.kind === 'folder' && t.name === 'LmdRootFixture'), 'drive root libraries retain descendant folder targets');
  assert.equal((await driveService.claim({ scope: 'recursive' })).groups.length, 1);
  add('06', 'season-work/Season 1'); add('07', 'season-work/Season 2');
  const oneSeason = await service.claim({ id: path.join('season-work', 'Season 1') });
  assert.equal(oneSeason.groups.length, 1, 'recursive selection of a season inside a grouped work stays usable');
  assert.equal(oneSeason.groups[0].episodes.length, 1, 'selecting a season must not include its sibling');
  assert.deepEqual(oneSeason.groups[0].context, [path.basename(root), 'season-work']);
  await service.release({ batchId: oneSeason.batchId });
  add('08', 'different/other');
  await assert.rejects(service.claim({ folder: 'other' }), /文件夹名称重复/);
  assert.throws(() => service.status({ folder: 'missing' }), /文件夹不存在/);
  await assert.rejects(service.claim({ folder: 'other', id: 'other' }), /只可指定一种/);
  assert.ok(!JSON.stringify(service.targets()).includes(root), 'hierarchy and range counts expose no media paths');
  const nestedRoot = path.join(directory, 'nested-library');
  const nestedApp = { libraries: [{ id: 'nested', path: nestedRoot }], displayGroups: [], media: [] };
  const nestedAdd = (id, folder) => nestedApp.media.push({ id, libraryId: 'nested', fileName: `${id}.mkv`, path: path.join(nestedRoot, folder, `${id}.mkv`), size: 10 });
  nestedAdd('menu-01', 'Show/menu'); nestedAdd('main-01', 'Show'); nestedAdd('main-02', 'Show'); nestedAdd('pv-01', 'Show/PV');
  const nestedOptions = { ...options, directory: path.join(directory, 'nested-labels'), getState: () => nestedApp, stableId: p => path.relative(nestedRoot, p) || 'nested-root' };
  let nested = await createLabelService(nestedOptions);
  const menu = await nested.claim({ id: path.join('Show', 'menu'), scope: 'direct' });
  await nested.apply({ batchId: menu.batchId, groups: [{ id: menu.groups[0].id, version: menu.groups[0].version, status: 'review', reason: '菜单单项名称不明' }] });
  assert.equal(nested.status().review, 1, 'a reviewed extra must not create an unrecorded review on its main episode group');
  assert.equal(nested.status().pending, 2, 'main episodes and a separate extra remain independently available');
  const main = await nested.claim({ id: 'nested-root', limit: 1 });
  assert.equal(main.groups[0].id, 'Show');
  assert.equal(main.groups[0].episodes.length, 2, 'a parent work excludes independently grouped extras');
  assert.deepEqual(main.groups[0].episodes.map(e => e.fileName), ['main-01.mkv', 'main-02.mkv'], 'per-slot basenames distinguish main episodes, duplicate encodes and extras without media paths');
  const pv = await nested.claim({ id: path.join('Show', 'PV'), scope: 'direct' });
  assert.equal(pv.groups.length, 1, 'non-overlapping parent and child work units can be claimed concurrently');
  assert.equal((await nested.claim({ id: 'nested-root' })).groups.length, 0, 'concurrent claims never duplicate members');
  await nested.apply(resultFor(main));
  assert.equal(nested.validate(resultFor(pv)).valid, true, 'a parent title does not invalidate an independently claimed extra');
  assert.equal(nested.media(nestedApp.media[0]).title, undefined, 'parent work titles do not silently mark reviewed extras complete');
  assert.equal(nested.media(nestedApp.media[1]).title, '吹响吧！上低音号');
  assert.equal(nested.media(nestedApp.media[2]).title, '吹响吧！上低音号', 'untitled episode slots inherit their correct work title');
  assert.ok(!JSON.stringify(nested.targets()).includes(nestedRoot));
  assert.ok(!JSON.stringify(nested.media(nestedApp.media[1])).includes(nestedRoot), 'private exclusion paths never enter public display payloads');
  assert.ok(!JSON.stringify(nested.folder(path.join(nestedRoot, 'Show'))).includes(nestedRoot), 'folder summaries do not leak partition paths');
  nestedAdd('main-03', 'Show');
  nested = await createLabelService(nestedOptions);
  assert.equal(nested.media(nestedApp.media[4]).title, '吹响吧！上低音号', 'new episodes remain protected after restart');
  assert.equal(nested.status().review, 1);
  await nested.apply(resultFor(pv));
  assert.equal(nested.status().completed, 2);
  assert.equal((await nested.claim({ id: 'nested-root' })).groups.length, 0);
  const retryMenu = await nested.claim({ id: path.join('Show', 'menu'), retry: true });
  assert.equal(retryMenu.groups.length, 1, 'only explicit review retry reopens the independent extra');
  const titleOnly = resultFor(retryMenu); delete titleOnly.groups[0].episodes;
  await nested.apply(titleOnly);
  assert.equal(nested.media(nestedApp.media[0]).title, '吹响吧！上低音号');
  assert.equal(nested.media(nestedApp.media[0]).originalEpisodeTitle, undefined, 'verified extra work titles may omit unknown single-item titles');
  nestedAdd('season-extra', 'Series/Season 1/Extras'); nestedAdd('season-main', 'Series/Season 1'); nestedAdd('other-season-main', 'Series/Season 2');
  const seasonRange = await nested.claim({ id: path.join('Series', 'Season 1') });
  assert.equal(seasonRange.groups.length, 2, 'a season containing extras still includes its main episodes when grouped under a parent');
  assert.deepEqual(seasonRange.groups.flatMap(g => g.episodes.map(e => e.fileName)).sort(), ['season-extra.mkv', 'season-main.mkv']);
  await nested.apply(resultFor(seasonRange));
  assert.equal(nested.media(nestedApp.media.at(-1)).title, undefined, 'season-specific application never expands into a sibling season');
  await nested.manual('Series', { title: '已确认系列' });
  assert.equal((await nested.claim({ id: 'Series' })).groups.length, 0, 'an existing manual ancestor title still protects every descendant');
  console.log('labels: concurrency, scopes, atomic group/episodes, legacy protection, new episodes, restart, conflict, review, expiry, validation passed');
} finally { await rm(directory, { recursive: true, force: true }); }
