import assert from "node:assert/strict";
import { readFile } from "node:fs/promises";
import vm from "node:vm";
import { cspInvokerSource, transformJassubCsp } from "../../tools/jassub-csp-transform.ts";
const scope = vm.createContext({ usesDestructorStack: (types: any[]) => types.slice(1).some(type => type && type.destructorFunction === undefined) }, { codeGeneration: { strings: false, wasm: false } });
vm.runInContext(cspInvokerSource, scope);
const returns = { isVoid: false }, simple = { destructorFunction: null };
const factory = scope.createJsInvoker([returns, null, simple, simple], false, true, false);
const fn = factory("sum", () => {}, (target: number, a: number, b: number) => target + a + b, 10, () => {}, (value: number) => value * 2, null, (_d: unknown, n: number) => n + 1, (_d: unknown, n: number) => n + 2);
assert.equal(fn(3, 4), 40); assert.equal(fn.length, 2);
const cleaned: unknown[] = [];
const method = scope.createJsInvoker([returns, { destructorFunction() {} }, simple], true, false, false)("method", () => {}, (_target: number, self: number, arg: number) => { assert.equal(self, 7); assert.equal(arg, 9); }, 0, () => {}, () => {}, (_d: unknown, value: { ptr: number }) => value.ptr, (_d: unknown, n: number) => n, (ptr: number) => cleaned.push(ptr));
assert.equal(method.call({ ptr: 7 }, 9), undefined); assert.deepEqual(cleaned, [7]);
const stackCleanup: unknown[] = [];
const stacked = scope.createJsInvoker([returns, null, {}], false, true, false)("stacked", () => {}, (_fn: number, value: number) => value, 0, (stack: unknown[]) => stackCleanup.push(...stack), (n: number) => n, null, (stack: unknown[], value: number) => { stack.push("owned", value); return value + 1; });
assert.equal(stacked(8), 9); assert.deepEqual(stackCleanup, ["owned", 8]);
const source = await readFile(new URL("../../node_modules/jassub/dist/wasm/jassub-worker.js", import.meta.url), "utf8");
const changed = transformJassubCsp(source, "/node_modules/jassub/dist/wasm/jassub-worker.js");
assert.ok(changed && !changed.includes("new Function("));
assert.equal(transformJassubCsp(source, "/other/file.js"), null);
assert.throws(() => transformJassubCsp("upstream changed", "/jassub/dist/wasm/jassub-worker.js"), /review CSP-safe/);
console.log("PASS: CSP-safe libass binding arguments, this, returns, destructors and upstream-change guard");
